spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/badbooks"
    username: admin
    password: passworld
    driver-class-name: org.postgresql.Driver